### ISSUE TITLE
Failure to parse string literals that use unicode quotes

### ISSUE THREAD

**Issue by urbanslug** [malcolmkiano/swahili#68]
**Describe the bug**
Could be confusing for beginners; the interperter can't parse unicode quotes for the string literal and doesn't give a very helpful error.
Found this by copying and pasting some code from I believe the docs but can't find it anymore.

**To Reproduce**
Running `andika(‟Hili ni neno”)`

fails with `Illegal Character: '‟'`

**Expected behavior**
The string should be parsed successfully.

**Comment by W3NDO** [comment]
We apologize for this. The Swahili interpreter does not support the unicode quotes. We will correct the the docs if and when we find the error.

**Comment by urbanslug** [comment]
What about considering it as a valid string? Would that be a bad thing?

**Comment by W3NDO** [comment]
it is a valid string if you use it inside a string, but you can't use it define a string. For instance:
```
andika(‟Hili ni neno”) // This is invalid
```

```
andika(" ‟Hili ni neno” ") // This is valid
```

**Comment by malcolmkiano** [comment]
@urbanslug just to make sure I'm tracking, you'd like to be able to use either `"string"` or `‟string”` for string literals?

**Comment by urbanslug** [comment]
Not at all. I thought many programming languages support the formation of string literals using such quotes, but it is not so. Plus, the error is relatively straightforward, so most people will figure out what they did wrong.

I was probably (and unknowingly) overeager with contributing.
