### ISSUE TITLE
Typo in `yoyote/tausworth` package

### ISSUE THREAD

**Issue by malcolmkiano** [malcolmkiano/swahili#94]
**Describe the bug**
Typo **"miwsho"** on line 34 of `swahili/bin/packages/yoyote/tausworth.js`

**Expected behavior**
Word should be **"mwisho"**

**Additional context**
Pointed out by @jasjastone

**Comment by jasjastone** [comment]
@malcolmkiano i  have already fix the issue on my pc should i commit the changes

**Comment by malcolmkiano** [comment]
@jasjastone this issue has been resolved in #95
